### ISSUE TITLE
Support for Azure Active Directory based authentication?

### ISSUE THREAD

**Issue by yunshiuan** [ServiceNow/AgentLab#184]
Do you know how I can support the LLM with Azure Active Directory based authentication?
It requires the following 4 keys

`AZURE_CLIENT_ID`
`AZURE_CLIENT_SECRET`
`AZURE_TENANT_ID`
`AZURE_OPENAI_API_BASE`

That is different from the API Key-based authentication, which requires `AZURE_OPENAI_API_KEY` and  `AZURE_OPENAI_ENDPOINT`.

**Comment by recursix** [comment]
I'm not familiar with active direcotry. Just adding these as environment variables is not sufficient? We may be able to add support if it's not too complex.

Could you give some usage examples?

**Comment by yunshiuan** [comment]
> Just adding these as environment variables is not sufficient?
No, I don't think so. When running the command `agentlab-assistant --start_url https://www.google.com`, it throws this error. It seems like it tries to find `OPENAI_API_KEY`.

```
OpenAIError:
The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
Traceback (most recent call last):
  File "~/conda/envs/return_m/lib/python3.11/site-packages/browsergym/experiments/loop.py", line 234, in run
    agent = self.agent_args.make_agent()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github_repos/test_agent_lab_m/src/agentlab/agents/generic_agent/generic_agent.py", line 68, in make_agent
    return GenericAgent(
           ^^^^^^^^^^^^^
  File "~/github_repos/test_agent_lab_m/src/agentlab/agents/generic_agent/generic_agent.py", line 82, in __init__
    self.chat_llm = chat_model_args.make_model()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/yunchuang/github_repos/test_agent_lab_m/src/agentlab/llm/chat_api.py", line 99, in make_model
    return OpenAIChatModel(
           ^^^^^^^^^^^^^^^^
  File "~/yunchuang/github_repos/test_agent_lab_m/src/agentlab/llm/chat_api.py", line 355, in __init__
    super().__init__(
  File "~/yunchuang/github_repos/test_agent_lab_m/src/agentlab/llm/chat_api.py", line 272, in __init__
    self.client = client_class(
                  ^^^^^^^^^^^^^
  File "~/conda/envs/return_m/lib/python3.11/site-packages/openai/_client.py", line 101, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

> Could you give some usage examples?
Many companies I know use Azure Active Directory based authentication for its higher security, as opposed to API Key-based authentication.

**Comment by yunshiuan** [comment]
Ok, I have solved this temporarily by rewriting the `__call__` function of the `ChatModel` class in the source file `src/agentlab/llm/chat_api.py`.

**Comment by recursix** [comment]
By default, it uses AGENT_4o_MINI, which uses openai API. If you change your agent for an agent that use a different LLM through --agent_config, it should work.
