### ISSUE TITLE
Issue with latest gradio version 5.4.0

### ISSUE THREAD

**Issue by imenelydiaker** [ServiceNow/AgentLab#98]
After a fresh install of the repo, launching xray produces the following error:

```sh
❯ agentlab-xray
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "/home/imeneker/dev/ui-copilot/.venv/bin/agentlab-xray", line 8, in <module>
    sys.exit(main())
  File "/home/imeneker/dev/ui-copilot/ui-assist/AgentLab/src/agentlab/analyze/agent_xray.py", line 1134, in main
    run_gradio(RESULTS_DIR)
  File "/home/imeneker/dev/ui-copilot/ui-assist/AgentLab/src/agentlab/analyze/agent_xray.py", line 223, in run_gradio
    agent_table = gr.DataFrame(height=500, show_label=False, interactive=False)
  File "/home/imeneker/dev/ui-copilot/.venv/lib/python3.10/site-packages/gradio/component_meta.py", line 179, in wrapper
    return fn(self, **kwargs)
TypeError: Dataframe.__init__() got an unexpected keyword argument 'height'
```
The argument changed to `max_height`  I think. With an older gradio version (4.41.0), I didn't have th issue. So maybe the version of gradio should be fixed in `requirements.txt`.

**Comment by recursix** [comment]
This should be fixed with main branch now. Could you confirm?
